# Generated by Django 4.1.5 on 2023-02-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
