# Generated by Django 4.1.5 on 2023-02-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_ware_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='image',
        ),
    ]
