# Generated by Django 4.1.5 on 2023-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_ware_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NPC',
        ),
    ]
