# Generated by Django 4.1.5 on 2023-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_delete_npc'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
